services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      - "start-dev"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
      - "--import-realm"
    volumes:
      - ./themes:/opt/keycloak/themes
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
